spring:
#  profiles:
#    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(BFc5hQDVrtKxWZWSW2ZC9zG5rffSiddBZ+CkMHc278jyAftB69UhfLipdH+EQp3mj4vwFms4hIj4XtDPvb3wectciQ5PLQXbCIAnSxy3dFjksovBqgdRlbb8xUTq3iTmfECOG3JO8D6V+WWhH778T1Y5e68yzscDFxHmBeWDBNbnGSOFncMEQQ==)
    #    jdbc:mysql://localhost:3306/DB_NAME?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ENC(phW6d7YIsNErj+8Ub9vkAg==)
    password: ENC(ql2W2noMkt+b/il6+6aVv/PNmXs/2JE8)
  jpa:
    hibernate:
      ddl-auto: update

upload:
  path: ENC(0TUPFuaCY/FVw5tX0o2dpUrAP/S/3Y0vq6hOGNFXz18=)
  url: ENC(2WMHR1abi7dAflO2WFkIWp87lp/xmilwnXBDpXgxsF1EjQUr9yg6H3jDoxHaCAVl)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

download:
#  path: ENC(2lGlh6YcZUd6G7BVL/zhyrlXgQ8mVlYl+xGhKE5sBdqUs3xUD4YCZzaPLJpqmZBJ) # ec2
  path: ENC(7Ei4ygdOu8Q7W2qXk3o7UJeDcFhKMXpgbfcX9q4ZS5gL2YdXZtNnNU8DiYUlm7aU+PLZ+Hs9HQk=) # lst ip
