spring:
  #  profiles:
  #    active: dev
  messages:
    basename: messages, errors
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/teamo3?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #    jdbc:mysql://localhost:3306/DB_NAME?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1235
  jpa:
    hibernate:
      ddl-auto: create
#      ddl-auto: update
    properties:
      hibernate:
#        format_sql: true
#        show_sql: true
#        highlight_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

server:
  servlet:
    session:
      tracking-modes: cookie

logging.level:
  org:
    hibernate.SQL: debug
    springframework:
      security: debug
#  org.hibernate.orm.jdbc.bind: trace
#      web.cors.DefaultCorsProcessor: trace # cors log

upload:
  path: ENC(AQ66smiFH5UC4uJ3+q/8jtHDQDKfebdjkW161ME4+Fef+seAkMdw9Mq7Cj8Ju07Z)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
